# Generated by Django 3.2.7 on 2021-10-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('situacao', models.CharField(blank=True, max_length=30, null=True)),
                ('conta_bancaria', models.CharField(blank=True, max_length=25, null=True)),
                ('contato_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('contato_email', models.CharField(blank=True, max_length=30, null=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
